"""Shared pytest fixtures.

Three things happen here that matter:

1. The test suite forces the hashing embedding backend. Tests must not
   depend on an 80 MB model download, must run identically in CI, and must
   produce the same numbers on every machine. Semantic quality is measured by
   the tuning script, not by unit tests.

2. The test suite hides any trained role-classifier artifact, for exactly the
   same reason. See `hidden_artifacts` below.

3. Every test gets its own SQLite file in a temp directory, so tests never
   see each other's rows and never touch the developer's database.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

BACKEND_ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"

# Make `app` importable without installing the package.
sys.path.insert(0, str(BACKEND_ROOT))

# Set before app.config is imported anywhere - Settings reads the environment
# at import time and caches the result.
os.environ.setdefault("APP_ENV", "test")
os.environ.setdefault("USE_TRANSFORMER_EMBEDDINGS", "false")


@pytest.fixture(scope="session", autouse=True)
def hidden_artifacts(tmp_path_factory):
    """Point `artifacts_dir` at an empty directory for the whole session.

    `artifacts/role_classifier.joblib` is generated by
    `scripts/train_classifier.py` and is not in git, so whether it exists is a
    property of the machine the suite runs on, not of the code. Without this
    fixture the suite passes on a clone and fails on the developer's box the
    moment they train a model - which is what S6.2 hit: two tests written
    against "there is no artifact" went red the first time there was one.

    Hiding it is the same call already made for embeddings one item above.
    Both are optional, both are large, both change results, and a test that
    reports different numbers depending on which optional artefact happens to
    be on disk is not a test. The trained backend is covered instead by stub
    bundles in `TestRoleClassification`, and end to end by
    `TestTrainClassifier`, which trains a real model into this same directory
    and deletes it again, so the isolation survives the one suite that wants
    the artifact to exist.

    Session-scoped and autouse, so no test can forget it.
    """
    from app.config import settings
    from app.core import classify

    empty = tmp_path_factory.mktemp("artifacts")
    # `artifacts_dir` is a cached_property, so patch the class attribute the
    # same way `temp_db` patches `database_file`.
    with pytest.MonkeyPatch.context() as patch:
        patch.setattr(type(settings), "artifacts_dir", property(lambda self: empty))
        # The loader is lru_cached, so a stale None (or a stale bundle) would
        # outlive the patch in either direction.
        classify._load_trained.cache_clear()
        yield empty
    classify._load_trained.cache_clear()


@pytest.fixture(scope="session")
def train_classifier_module():
    """`scripts/train_classifier.py`, imported as a module.

    Skips where scikit-learn is missing. It is an ML extra, not a required
    dependency, and the suite has to stay green in the degraded environment -
    the one where the profile classifier is not the fallback but the whole
    implementation.
    """
    pytest.importorskip("sklearn")
    pytest.importorskip("joblib")

    import importlib.util

    path = BACKEND_ROOT / "scripts" / "train_classifier.py"
    spec = importlib.util.spec_from_file_location("train_classifier", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="session")
def import_jobs_module():
    """`scripts/import_jobs.py`, imported as a module.

    No `importorskip` here, unlike `train_classifier_module` above: the
    importer is stdlib and `app.core.jobs_data` only, so it has to work in the
    degraded environment. Growing the corpus is not an ML extra.
    """
    import importlib.util

    path = BACKEND_ROOT / "scripts" / "import_jobs.py"
    spec = importlib.util.spec_from_file_location("import_jobs", path)
    module = importlib.util.module_from_spec(spec)
    # Registered before `exec_module`, unlike `train_classifier_module` above,
    # because this script defines a dataclass under `from __future__ import
    # annotations`. `@dataclass` resolves its string annotations by looking its
    # own module up in `sys.modules`, and a module that is not in there yet
    # fails with an AttributeError on None at import time.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="session")
def tune_weights_module():
    """`scripts/tune_weights.py`, imported as a module.

    No `importorskip`, for the same reason as `import_jobs_module`: the tuner
    is stdlib and `app.core` only. Choosing the weights is not an ML extra,
    and the degraded environment is the one where getting them right matters
    most - it is the only signal the hashing backend has a lot of.
    """
    import importlib.util

    path = BACKEND_ROOT / "scripts" / "tune_weights.py"
    spec = importlib.util.spec_from_file_location("tune_weights", path)
    module = importlib.util.module_from_spec(spec)
    # Registered before `exec_module`, like `import_jobs_module`: this script
    # also defines dataclasses under `from __future__ import annotations`.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="session")
def sample_resume_text() -> str:
    """A complete, well-formed resume. The happy path for every stage."""
    return (FIXTURES / "sample_resume.txt").read_text(encoding="utf-8")


@pytest.fixture(scope="session")
def sample_resume_bytes(sample_resume_text: str) -> bytes:
    return sample_resume_text.encode("utf-8")


@pytest.fixture(scope="session")
def weak_resume_text() -> str:
    """A deliberately bad resume.

    Every ATS rule should score low on this: no contact block, no headings,
    no bullets, no numbers, clichés, first person, inconsistent dates. It is
    the negative control - without it a rule that always returns full marks
    would pass every test.
    """
    return (FIXTURES / "weak_resume.txt").read_text(encoding="utf-8")


@pytest.fixture(scope="session")
def backend_jd() -> str:
    """A backend job description with an explicit requirements list."""
    return (FIXTURES / "backend_jd.txt").read_text(encoding="utf-8")


@pytest.fixture(scope="session")
def design_jd() -> str:
    """A job description with almost no overlap with the sample resume.

    Used to assert that matching actually discriminates - a scorer that
    returns 70 for everything passes any test that only checks one pairing.
    """
    return (FIXTURES / "design_jd.txt").read_text(encoding="utf-8")


@pytest.fixture()
def temp_db(tmp_path, monkeypatch):
    """Point the store at a throwaway SQLite file for one test."""
    from app.config import settings
    from app import store

    database = tmp_path / "test.db"
    # `database_file` is a cached_property, so patch the cached value directly.
    monkeypatch.setattr(
        type(settings), "database_file", property(lambda self: database)
    )
    store.init_db()
    return database


@pytest.fixture()
def client(temp_db):
    """A FastAPI test client with an isolated database.

    Uses TestClient as a context manager so the lifespan hook runs - without
    that, warmup never happens and /api/health reports empty components.
    """
    from fastapi.testclient import TestClient

    from app.main import app

    with TestClient(app) as test_client:
        yield test_client
